language: rust
sudo: false
cache: cargo
rust:
- stable
- beta
- nightly
env:
- COMPILE_ARGS=("--no-default-features")
- COMPILE_ARGS=()
os:
- linux
- osx
before_script:
- export PATH="$PATH:$HOME/.cargo/bin"
- which rustfmt || cargo install rustfmt --vers 0.7.1
- rustfmt --version
script:
- cargo build --verbose "${COMPILE_ARGS[@]}"
- cargo fmt --verbose -- --write-mode=diff
- cargo test --verbose "${COMPILE_ARGS[@]}" -- --skip auth
