language: rust
sudo: false
cache: cargo
rust:
- stable
- beta
- nightly
os:
- linux
- osx
script:
- cargo build --verbose
- cargo test --verbose -- --skip auth
- cargo build --verbose --no-default-features
- cargo test --verbose --no-default-features -- --skip auth
