language: rust
sudo: false
rust:
- stable
- beta
- nightly
cache: cargo
before_script:
- export PATH="$PATH:$HOME/.cargo/bin"
- which rustfmt || cargo install rustfmt --vers 0.7.1
script:
- cargo fmt -- --write-mode=diff
- |
  if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
    echo "WARNING: Tests requiring authentication disabled";
    cargo test -- --skip auth
  else
    cargo test
  fi
matrix:
  allow_failures:
  - rust: nightly
