language: rust
sudo: false
cache: cargo
matrix:
    allow_failures:
    - rust: nightly
    include:
    - rust: stable
      env:
      - TEST_ARGS=("parse")
    - rust: beta
    - rust: beta
      env:
      - TEST_ARGS=("parse")
      - COMPILE_ARGS=("--no-default-features")
    - rust: nightly
      env:
      - TEST_ARGS=("parse")
before_script:
- export PATH="$PATH:$HOME/.cargo/bin"
- which rustfmt || cargo install rustfmt --vers 0.7.1
- |
    if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then
        echo "WARNING: Tests requiring authentication disabled."
        if [ "$TEST_ARGS" != "parse" ]; then
            TEST_ARGS=("--", "--skip" "auth")
        fi
    fi
script:
- cargo build --verbose "${COMPILE_ARGS[@]}"
- cargo fmt --verbose -- --write-mode=diff
- cargo test --verbose "${COMPILE_ARGS[@]}" "${TEST_ARGS[@]}"
