language: rust
sudo: false
cache: cargo
rust:
- stable
- beta
- nightly
env:
- COMPILE_ARGS=("--no-default-features")
- COMPILE_ARGS=()
os:
- linux
- osx
script:
- cargo build --verbose "${COMPILE_ARGS[@]}"
- cargo test --verbose "${COMPILE_ARGS[@]}" -- --skip auth
