# Based on the "trust" template v0.1.1
# https://github.com/japaric/trust/tree/v0.1.1

# Note: we're explicitly only supporting MSVC and not MinGW here due to ring's support for MSCV.
environment:
    matrix:
    # Stable
    - TARGET: i686-pc-windows-msvc
      RUST_VERSION: stable
    - TARGET: x86_64-pc-windows-msvc
      RUST_VERSION: stable
    # Beta
    - TARGET: i686-pc-windows-msvc
      RUST_VERSION: beta
    - TARGET: x86_64-pc-windows-msvc
      RUST_VERSION: beta
    # Nightly
    - TARGET: i686-pc-windows-msvc
      RUST_VERSION: nightly
    - TARGET: x86_64-pc-windows-msvc
      RUST_VERSION: nightly

install:
- curl -sSf -o rustup-init.exe https://win.rustup.rs/
- rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
- set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
- rustc -Vv
- cargo -V

test_script:
- cargo build --verbose --target %TARGET%
- cargo test --verbose --target %TARGET% -- --skip auth
- cargo build --verbose --target %TARGET% --no-default-features
- cargo test --verbose --target %TARGET% --no-default-features -- --skip auth

cache:
- target

# Disable the appveyor build step so we can just build the rust project instead.
build: off
