[package]
name = "screeps-api"
version = "0.1.1-dev"
authors = ["Dabo Ross <daboross@daboross.net>"]
description = "Fully typed and tested wrapper over the Screeps Game's HTTP API"

documentation = "http://dabo.guru/rust/screeps-api/"
repository = "https://github.com/daboross/rust-screeps-api"

readme = "README.md"

keywords = ["screeps"]
categories = ["api-bindings"]
license = "MIT"

[badges]
travis-ci = { repository = "daboross/rust-screeps-api", branch = "master" }
appveyor = { service = "github", repository = "daboross/rust-screeps-api", branch = "master" }

[dependencies]
log = "0.3"
url = "1.0"
hyper = "0.10"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_ignored = "0.0.4"
serde-tuple-vec-map = "0.2"
time = "0.1"
# generic-array 0.5 needed for arrayvec support.
generic-array = "0.5"
typenum = "1.0"
arrayvec = { version = "0.3", features = ["use_generic_array"] }
ws = { version = "0.7", features = ["ssl"], optional = true }
fnv = { version = "1.0", optional = true }
rand = { version = "0.3", optional = true }

[features]
websockets = ["ws", "fnv", "rand"]
default = ["websockets"]

[dev-dependencies]
dotenv = "0.10"
hyper-rustls = "0.6"
fern = "0.4"
chrono = "0.3"
clap = "2.22"

[[example]]
name = "ws-debug"
required-features = ["ws"]

[[example]]
name = "me"

[[example]]
name = "top10"
