[package]
name = "screeps-api"
version = "0.1.0"
authors = ["Dabo Ross <daboross@daboross.net>"]

[dependencies]
hyper = "0.10"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
time = "0.1"

[dev-dependencies]
dotenv = "0.8"
hyper-rustls = "0.3"
