[package]
name = "screeps-api"
version = "0.1.2-dev"
authors = ["Dabo Ross <daboross@daboross.net>"]
description = "Fully typed and tested wrapper over the Screeps Game's HTTP API"

documentation = "http://dabo.guru/rust/screeps-api/"
repository = "https://github.com/daboross/rust-screeps-api"

readme = "README.md"

keywords = ["screeps"]
categories = ["api-bindings"]
license = "MIT"

[badges]
travis-ci = { repository = "daboross/rust-screeps-api", branch = "master" }
appveyor = { service = "github", repository = "daboross/rust-screeps-api", branch = "master" }

[dependencies]
# Logging
log = "0.3"
time = "0.1"
# Parsing
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_ignored = "0.0.4"
serde-tuple-vec-map = "0.2"
typenum = "1.0"
generic-array = "0.5"
arrayvec = { version = "0.3", features = ["use_generic_array"] }
# HTTP
futures = "0.1"
url = "1.0"
hyper = { git = "https://github.com/hyperium/hyper.git" }
# Sync HTTP wrapper
tokio-core = { version = "", optional = true }
hyper-tls = { git = "https://github.com/hyperium/hyper-tls.git", optional = true }
# Sockets
fnv = { version = "1.0", optional = true }
rand = { version = "0.3", optional = true }
ws = { version = "0.7", features = ["ssl"], optional = true }

[features]
sync = ["tokio-core", "hyper-tls"]
websockets = ["ws", "fnv", "rand"]
default = ["websockets", "sync"]

[dev-dependencies]
dotenv = "0.10"
fern = "0.4"
chrono = "0.3"
clap = "2.22"

[[example]]
name = "ws-debug"
required-features = ["sync", "websockets"]

[[example]]
name = "me"
required-features = ["sync"]

[[example]]
name = "top10"
required-features = ["sync"]
