[package]
name = "screeps-api"
version = "0.3.1"
authors = ["David Ross <daboross@daboross.net>"]
description = "Fully typed and tested wrapper over the Screeps Game's HTTP API"

documentation = "https://dabo.guru/rust/screeps-api/"
repository = "https://github.com/daboross/rust-screeps-api"

readme = "README.md"

license = "MIT"
keywords = ["screeps"]
categories = ["api-bindings"]

include = ["Cargo.toml", "src/**/*", "tests/**/*", "examples/**/*", "LICENSE", "README.md"]

[package.metadata.docs.rs]
all-features = true

[badges]
travis-ci = { repository = "daboross/rust-screeps-api", branch = "master" }
appveyor = { service = "github", repository = "daboross/rust-screeps-api", branch = "master" }

[dependencies]
# Logging
log = "0.4"
# Parsing
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_ignored = "0.0.4"
serde-tuple-vec-map = "0.2"
arrayvec = "0.4"
time = "0.1"
# HTTP
futures = "0.1"
url = "1.0"
hyper = "0.11"
# Sync HTTP wrapper
tokio-core = { version = "0.1", optional = true }
hyper-tls = { version = "0.1", optional = true }
native-tls = { version = "0.1", optional = true }
# Websockets
rand = "0.4"

[features]
sync = ["tokio-core", "hyper-tls", "native-tls"]
default = ["sync"]

[dev-dependencies]
# .env parsing
dotenv = "0.10"
# logging in examples
fern = "0.5"
chrono = "0.4"
# cli options in examples
clap = "2.22"
# socket connections in ws-debug example
tokio-core = "0.1"
futures = "0.1"
websocket = "0.20.1"
# pretty printing in ws-debug.
serde_json = "1.0"

[[example]]
name = "ws-debug"
required-features = ["sync"]

[[example]]
name = "me"
required-features = ["sync"]

[[example]]
name = "top10"
required-features = ["sync"]

[[example]]
name = "ws-console"
required-features = ["sync"]
