max_width = 120
ideal_width = 110
fn_single_line = true
fn_args_paren_newline = false
report_fixme = "unnumbered"
reorder_imports = true
reorder_import_names = true
format_strings = false
normalize_comments = true
use_try_shorthand = true
write_mode = "overwrite"
condense_wildcard_suffices = true
